import exp from "constants";

export const table_columns = [
  'vin',
  'county',
  'city',
  'state',
  'postal_code',
  'model_year',
  'make',
  'model',
  'electric_vehicle_type',
  'cafv_eligibility',
  'electric_range',
  'base_msrp',
  'legislative_district',
  'dol_vehicle_id',
  'vehicle_location',
  'electric_utility',
  'census_tract_2020'
];

export const county_columns = ["Kings",
    "Jefferson",
    "Grant",
    "Cowlitz",
    "Wahkiakum",
    "Okanogan",
    "Columbia",
    "Kittitas",
    "Wake",
    "Walla Walla",
    "Christian",
    "Franklin",
    "Maricopa",
    "Ferry",
    "Laramie",
    "District of Columbia",
    "Santa Clara",
    "Pacific",
    "Adams",
    "Clallam",
    "King",
    "El Paso",
    "Brevard",
    "Lee",
    "Pend Oreille",
    "Virginia Beach",
    "Chelan",
    "San Juan",
    "Benton",
    "Snohomish",
    "Asotin",
    "Beaufort",
    "Howard",
    "Klickitat",
    "Lincoln",
    "Orange",
    "Hardin",
    "Grays Harbor",
    "Pierce",
    "Spokane",
    "Meade",
    "Harnett",
    "Skamania",
    "Whitman",
    "Clark",
    "Kitsap",
    "Fairfax",
    "Thurston",
    "San Diego",
    "Island",
    "Mason",
    "Skagit",
    "DeKalb",
    "Los Angeles",
    "Anne Arundel",
    "Douglas",
    "Stevens",
    "Lewis",
    "Whatcom",
    "Hamilton",
    "Prince George's",
    "San Mateo",
    "Yakima",
    "Currituck",
    "Wasco",
    "Calvert",
    "Loudoun"
    ]


export const make_columns = ["GMC",
        "VOLKSWAGEN",
        "ALFA ROMEO",
        "DODGE",
        "LUCID",
        "FORD",
        "CHRYSLER",
        "NISSAN",
        "MINI",
        "ROLLS-ROYCE",
        "CADILLAC",
        "SUBARU",
        "POLESTAR",
        "LEXUS",
        "MULLEN AUTOMOTIVE INC.",
        "TOYOTA",
        "JAGUAR",
        "MERCEDES-BENZ",
        "RIVIAN",
        "TH!NK",
        "WHEEGO ELECTRIC CARS",
        "JEEP",
        "AUDI",
        "CHEVROLET",
        "PORSCHE",
        "MITSUBISHI",
        "BENTLEY",
        "LINCOLN",
        "FISKER",
        "KIA",
        "MAZDA",
        "HONDA",
        "ACURA",
        "TESLA",
        "FIAT",
        "GENESIS",
        "VINFAST",
        "LAND ROVER",
        "SMART",
        "BMW",
        "VOLVO",
        "HYUNDAI",
        "AZURE DYNAMICS",
        "BRIGHTDROP",
        "LAMBORGHINI"
    ]


export const electric_vehicle_type_columns = ["Plug-in Hybrid Electric Vehicle (PHEV)",
"Battery Electric Vehicle (BEV)"

]

export const electric_range_columns = [

]